name: Deploy Tarot Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restart Bot with actual project path
        run: |
          # Переходим в рабочую папку, где лежит ваш .env и конфиги
          cd /home/botrunner/tarot-bot
          
          # Останавливаем старые контейнеры
          docker compose down
          
          # Собираем и запускаем заново
          # Мы используем путь к папке .github/workflows/.. для актуального кода
          docker compose up -d --build
          
