name: Deploy Tarot Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy
        run: |
          # Переходим в директорию репозитория (автоматическая переменная GitHub)
          # Это гарантирует, что контекст сборки будет содержать только файлы проекта
          cd ${{ github.workspace }}
          
          # Останавливаем старые контейнеры
          docker compose down
          
          # Собираем и запускаем заново
          # Кэш образов будет использован, если зависимости не изменились
          docker compose up -d --build
          
          # (Опционально) Удаляем висящие образы для экономии места на диске
          docker image prune -f
